name: Update Discussion Board

on:
  workflow_run:
    workflows: ["Interact with Site"]
    types:
      - completed

jobs:
  update-discussion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update Discussion Board
      run: node scripts/update-discussion-board.js
      env:
        GITHUB_TOKEN: ${{ secrets.PR_CYBR_ACTIONS }}