# Example secrets file
# Rename this file to secrets.yml and populate with actual secret values
# Values can be dynamically updated from a local .env file during setup

# OpenAI API Key
openai_api_key: '${OPENAI_API_KEY}'

# Docker Hub Credentials
docker_username: '${DOCKER_USERNAME}'
docker_password: '${DOCKER_PASSWORD}'

# Database Credentials
db_host: '${DB_HOST}'
db_port: '${DB_PORT}'
db_name: '${DB_NAME}'
db_user: '${DB_USER}'
db_password: '${DB_PASSWORD}'

# OAuth2 Credentials
oauth_client_id: '${OAUTH_CLIENT_ID}'
oauth_client_secret: '${OAUTH_CLIENT_SECRET}'

# Other API Keys
external_service_api_key: '${EXTERNAL_SERVICE_API_KEY}'

# Encryption Keys
encryption_key: '${ENCRYPTION_KEY}'

# Flask configuration
flask_env: '${FLASK_ENV}'
flask_debug: '${FLASK_DEBUG}'

# Agent configuration
assistant_id: '${ASSISTANT_ID}'

# API keys and secrets
api_key: '${API_KEY}'
secret_key: '${SECRET_KEY}'

# Github config
github_token: '${GITHUB_TOKEN}'

# Slack config
slack_bot_token: '${SLACK_BOT_TOKEN}'
slack_channel_name: '${SLACK_CHANNEL_NAME}'

# Domain Info
domain_name: '${DOMAIN_NAME}'
ssl_email: '${SSL_EMAIL}'

# N8N Config
n8n_host: '${N8N_HOST}'
n8n_port: '${N8N_PORT}'
n8n_basic_auth_user: '${N8N_BASIC_AUTH_USER}'
n8n_basic_auth_password: '${N8N_BASIC_AUTH_PASSWORD}'

# NGINX Config
nginx_conf: '${NGINX_CONF}'

# Zerotier Config
zerotier_ip: '${ZEROTIER_IP}'
zerotier_id: '${ZEROTIER_ID}'

# Database configuration for n8n
db_postgresdb_database: '${DB_POSTGRESDB_DATABASE}'
db_postgresdb_user: '${DB_POSTGRESDB_USER}'
db_postgresdb_password: '${DB_POSTGRESDB_PASSWORD}'

# Timezone configuration
n8n_tz: '${N8N_TZ}'

# Logging configuration
log_level: '${LOG_LEVEL}'

# CORS configuration
cors_allowed_origins: '${CORS_ALLOWED_ORIGINS}'

# External service URLs
external_service_url: '${EXTERNAL_SERVICE_URL}'

# Note: Ensure that this file is not included in version control.
# Use this template to create a secrets.yml file with actual secret values.
# During setup, use a script to replace placeholders with values from the .env file.