# Configuration settings for the PR-CYBR-MGMT-AGENT

# General settings
agent_id: "${AGENT_ID}"
log_level: "${LOG_LEVEL}"

# Strategic planning settings
strategic_plan_frequency: "${STRATEGIC_PLAN_FREQUENCY}"
default_objectives:
  - "Enhance cybersecurity awareness"
  - "Improve inter-agent collaboration"
  - "Optimize resource allocation"

# Coordination settings
task_assignment_algorithm: "${TASK_ASSIGNMENT_ALGORITHM}"
dependency_check_interval: "${DEPENDENCY_CHECK_INTERVAL}"

# Monitoring and reporting settings
report_generation_frequency: "${REPORT_GENERATION_FREQUENCY}"
alert_thresholds:
  progress_delay: "${PROGRESS_DELAY_THRESHOLD}"
  resource_utilization: "${RESOURCE_UTILIZATION_THRESHOLD}"

# Decision support settings
priority_criteria:
  - "impact"
  - "urgency"
  - "resource_availability"

# Data management settings
data_retention_period: "${DATA_RETENTION_PERIOD}"
secure_data_storage: "${SECURE_DATA_STORAGE}"

# API settings
api_host: "${API_HOST}"
api_port: "${API_PORT}"
enable_cors: "${ENABLE_CORS}"

# Docker settings
docker_image_name: "${DOCKER_IMAGE_NAME}"
docker_network: "${DOCKER_NETWORK}"

# Authentication settings
enable_authentication: "${ENABLE_AUTHENTICATION}"
auth_method: "${AUTH_METHOD}"

# Flask configuration
flask_env: "${FLASK_ENV}"
flask_debug: "${FLASK_DEBUG}"

# Agent configuration
assistant_id: "${ASSISTANT_ID}"

# Domain Info
domain_name: "${DOMAIN_NAME}"
ssl_email: "${SSL_EMAIL}"

# N8N Config
n8n_host: "${N8N_HOST}"
n8n_port: "${N8N_PORT}"
n8n_basic_auth_user: "${N8N_BASIC_AUTH_USER}"
n8n_basic_auth_password: "${N8N_BASIC_AUTH_PASSWORD}"

# NGINX Config
nginx_conf: "${NGINX_CONF}"

# Zerotier Config
zerotier_ip: "${ZEROTIER_IP}"
zerotier_id: "${ZEROTIER_ID}"

# Timezone configuration
n8n_tz: "${N8N_TZ}"

# CORS configuration
cors_allowed_origins: "${CORS_ALLOWED_ORIGINS}"

# External service URLs
external_service_url: "${EXTERNAL_SERVICE_URL}"

# Note: The following settings and their corresponding functions must be created and updated
# via the OpenAI Platform Dashboard to ensure proper integration and functionality.
# Ensure that the necessary API endpoints, authentication mechanisms, and data handling
# processes are defined and tested within the OpenAI environment.

# Additional settings can be added as needed