name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tasks:
        description: 'Comma-separated list of tasks to run (e.g., build,test,deploy)'
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        if: contains(github.event.inputs.tasks || 'build,test,deploy', 'test')
        run: |
          python -m unittest discover tests

      - name: Run security checks
        if: contains(github.event.inputs.tasks || 'build,test,deploy', 'security')
        run: |
          pip install bandit
          bandit -r src

  build-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: contains(github.event.inputs.tasks || 'build,test,deploy', 'build')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/$AGENT_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    if: contains(github.event.inputs.tasks || 'build,test,deploy', 'deploy')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying to production environment..."
          # Add deployment commands here, e.g., kubectl apply -f deployment.yaml