name: Test and Deploy Static Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: List installed packages for debugging
      run: ls -l node_modules/html-webpack-plugin

    - name: Run status-page tests
      run: npm test -- src/js/__tests__/status-page.test.js

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build

    - name: Deploy to main branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add dist # Add the built files
        git commit -m "Deploy static files" || echo "No changes to commit"
        git push origin main || echo "Nothing to push"