name: Test and Deploy Static Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run status-page tests
      run: npm test -- src/js/__tests__/status-page.test.js # Ensure this path is correct

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: ls -R src/templates # Adjust this path as needed

    - name: Deploy static files to main branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add src/templates # Ensure this path is correct and files exist
        git commit -m "Deploy static files" || echo "No changes to commit"
        git push origin main || echo "Nothing to push"