name: Test and Deploy Static Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run status-page tests
      run: npm test -- src/js/__tests__/status-page.test.js # Ensure this path is correct

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy static files to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PR_CYBR_ACTIONS }}
        publish_dir: ./src/templates

    - name: Create a tag to trigger Webpack workflow
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag -a deploy-success -m "Trigger Webpack build"
        git push origin deploy-success