name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: |
        # If you have a build step, include it here
        # For example, if using a static site generator like Jekyll or Hugo, run the build command
        # If no build step is needed, you can skip this step

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PR_CYBR_ACTIONS }}
        publish_dir: ./web/templates  # Directory containing your status.html and other static files