name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Build and Deploy with Webpack"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version tag
      id: extract_tag
      run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: prcybr/pr-cybr-mgmt-agent:${{ env.TAG }}

    - name: Verify image
      run: docker pull prcybr/pr-cybr-mgmt-agent:${{ env.TAG }}