name: OpenAI Function Integration

on:
  workflow_dispatch:
    inputs:
      function_name:
        description: 'Name of the OpenAI function to call'
        required: true
      parameters:
        description: 'Parameters for the function call in JSON format'
        required: false
  push:
    branches:
      - main

jobs:
  call_openai_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Call OpenAI Function
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -c "
          import openai
          import json

          openai.api_key = '${{ secrets.OPENAI_API_KEY }}'

          function_name = '${{ github.event.inputs.function_name }}'
          parameters = json.loads('${{ github.event.inputs.parameters }}' or '{}')

          function_call = {
              'name': function_name,
              'parameters': parameters
          }

          response = openai.ChatCompletion.create(
              model='gpt-4o-mini',
              messages=[
                  {'role': 'user', 'content': f'Execute function {function_name}.'}
              ],
              functions=[function_call],
              function_call='auto'
          )
          print(response)
          "