name: tfc-sync

on:
  push:
    branches:
      - codex     # AI-driven commits (Codex Platform)
      - agents    # Agent-driven inter-repo commits
  pull_request:
    branches:
      - main      # All PRs targeting main branch (HITL control)

permissions:
  contents: read
  id-token: write   # Prepares for Terraform Cloud OIDC auth

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TFC_ORG: pr_cybr
      TFC_WORKSPACE: A-10
      TFC_API_URL: https://app.terraform.io/api/v2
      TF_VAR_TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
      TF_VAR_NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧠 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: 🔍 Fetch workspace variables from Terraform Cloud
        id: tf-vars
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
        run: |
          echo "Fetching variables from Terraform Cloud workspace: $TFC_WORKSPACE"
          curl -s \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            "$TFC_API_URL/organizations/$TFC_ORG/workspaces/$TFC_WORKSPACE/vars" \
            | jq -r '.data[].attributes.key' > workspace_vars.txt

          echo "Variables defined in Terraform Cloud:"
          cat workspace_vars.txt

      - name: 🧹 Export matching workspace variables to environment
        run: |
          echo "Syncing environment variables..."
          while read -r key; do
            # Check if variable exists as a GitHub Actions env var or secret
            if [ -n "${!key}" ]; then
              echo "✅ Exporting $key"
              echo "$key=${!key}" >> $GITHUB_ENV
            else
              echo "⚠️ Skipping undefined variable: $key"
            fi
          done < workspace_vars.txt

      - name: 🧩 Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: 🧮 Terraform Plan
        working-directory: ./infra
        run: terraform plan -input=false -no-color

      - name: 🚀 Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./infra
        run: terraform apply -auto-approve -input=false

      - name: 🧾 Summary Log
        if: always()
        run: |
          echo "=============================="
          echo "Synced environment variables:"
          printenv | grep NOTION || true
          echo "=============================="
